### ISSUE TITLE
Incompatible with the VapourSynth R66

### ISSUE THREAD

**Issue by RyougiKukoc** [HomeOfVapourSynthEvolution/VapourSynth-BM3D#30]
Test on Windows10 Python 3.12 VapourSynth R66
```python
from vapoursynth import core
core.LoadPlugin("bm3d.dll")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\\cython\\vapoursynth.pyx", line 3110, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load D:\WPy64-31241+VapourSynth\python-3.12.4.amd64\vs-plugins\BM3D.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```

**Comment by RyougiKukoc** [comment]
Never mind, forgot libfftw3f-3.dll
